### ISSUE TITLE
HISTO-51 Implement lifecycle save/restore

### ISSUE THREAD

**Issue by nogueirasjorge** [nogueirasjorge/histora-project#55]

**Comment by fedemoglia** [comment]
We already have a task with _[HISTO-51](https://trello.com/c/TEu3X664/269-histo-51-agregar-trivia-en-escena-de-mastil-unlam)_ key, but the branch was not created by @santiagons yet. Maybe he is working on trivia-test branch. We should ensure it.
Is this to avoid the problem that I couldn't reproduce yesterday, it isn't?

**Comment by nogueirasjorge** [comment]
I think it should fix that problem. About keys, it does not matter if we are having the same issue keys in another project. If that ticket belongs to this project, should be created first in here, as an issue. If not, there is no problah ;)
